version: '3.8'
services:

#  gateway:
#    build: ./gateway
#    ports:
#      - "8080:8000"

  employee_service_db:
    image: mysql:8
    container_name: employee_service_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_EMPLOYEE_SERVICE_DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  employee-service:
    build:
      context: ./services/employee-service
      dockerfile: Dockerfile
    container_name: employee-service
    ports:
      - "8081:8080"
    depends_on:
      - employee_service_db
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_EMPLOYEE_SERVICE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend

  leave_service_db:
    image: mysql:8
    container_name: leave_service_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_LEAVE_SERVICE_DB_NAME}
    ports:
      - "3308:3306"
    volumes:
      - leave_service_mysql-data:/var/lib/mysql
    networks:
      - backend

  leave-service:
    build:
      context: ./services/leave-service
      dockerfile: Dockerfile
    container_name: leave-service
    ports:
      - "8082:8080"
    depends_on:
      - leave_service_db
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_LEAVE_SERVICE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend

volumes:
  mysql-data:
  leave_service_mysql-data:

networks:
  backend: