services:

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - employee-service
      - leave-service
      - jwt-service
      - password-service
    networks:
      - backend

  employee-service-db:
    image: mysql:8
    container_name: employee_service_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_EMPLOYEE_SERVICE_DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  employee-service:
    build:
      context: ./services/employee-service
      dockerfile: Dockerfile
    container_name: employee-service
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - employee-service-db
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_EMPLOYEE_SERVICE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend

  leave-service-db:
    image: mysql:8
    container_name: leave_service_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_LEAVE_SERVICE_DB_NAME}
    ports:
      - "3308:3306"
    volumes:
      - leave_service_mysql-data:/var/lib/mysql
    networks:
      - backend

  leave-service:
    build:
      context: ./services/leave-service
      dockerfile: Dockerfile
    container_name: leave-service
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - leave-service-db
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_LEAVE_SERVICE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend

  # New Approval Service
  approval_service_db:
    image: mysql:8
    container_name: approval_service_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_APPROVAL_SERVICE_DB_NAME}
    ports:
      - "3309:3306"
    volumes:
      - approval_service_mysql-data:/var/lib/mysql
    networks:
      - backend

  approval-service:
    build:
      context: ./services/approval-service
      dockerfile: Dockerfile
    container_name: approval-service
    ports:
      - "8083:8080"
    depends_on:
      - approval_service_db
      - employee-service
      - leave-service
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_APPROVAL_SERVICE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      EMPLOYEE_SERVICE_URL: http://employee-service:8080
      LEAVE_SERVICE_URL: http://leave-service:8080
      
  jwt-service:
    build:
      context: ./services/jwt-service
      dockerfile: Dockerfile
    container_name: jwt-service
    restart: always
    ports:
      - "8083:8080"
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_TIME_BY_SECOND: ${JWT_EXPIRATION_TIME_BY_SECOND}
    networks:
      - backend

  password-service:
    build:
      context: ./services/password-service
      dockerfile: Dockerfile
    container_name: password-service
    restart: always
    ports:
      - "8084:8080"
    networks:
      - backend

volumes:
  mysql-data:
  leave_service_mysql-data:
  approval_service_mysql-data:

networks:
  backend:
    driver: bridge